<?php

namespace ContainerLMbeHe8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EZDPmrfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eZDPmrf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eZDPmrf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'saveProduct' => ['privates', 'App\\Service\\SaveProduct', 'getSaveProductService', true],
        ], [
            'saveProduct' => 'App\\Service\\SaveProduct',
        ]);
    }
}
