<?php

namespace ContainerWP6s19a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonolog_Logger_AddProductService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'monolog.logger.addProduct' shared service.
     *
     * @return \Symfony\Bridge\Monolog\Logger
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['monolog.logger.addProduct'] = $instance = new \Symfony\Bridge\Monolog\Logger('addProduct');

        $instance->pushHandler(($container->privates['monolog.handler.console'] ?? $container->getMonolog_Handler_ConsoleService()));
        $instance->pushHandler(($container->privates['monolog.handler.product'] ?? $container->load('getMonolog_Handler_ProductService')));

        return $instance;
    }
}
