<?php

namespace ContainerWP6s19a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSaveProductService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SaveProduct' shared autowired service.
     *
     * @return \App\Service\SaveProduct
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SaveProduct.php';

        return $container->privates['App\\Service\\SaveProduct'] = new \App\Service\SaveProduct(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['monolog.logger.addProduct'] ?? $container->load('getMonolog_Logger_AddProductService')));
    }
}
