<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWP6s19a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWP6s19a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWP6s19a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWP6s19a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWP6s19a\App_KernelDevDebugContainer([
    'container.build_hash' => 'WP6s19a',
    'container.build_id' => '60a73401',
    'container.build_time' => 1636944453,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWP6s19a');
